# Generated by Django 5.0.1 on 2025-11-26 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('skills', models.JSONField(default=list, help_text='List of skills', verbose_name='skills')),
                ('education', models.JSONField(default=list, help_text='Education history', verbose_name='education')),
                ('experience', models.JSONField(default=list, help_text='Work experience', verbose_name='experience')),
                ('certifications', models.JSONField(default=list, verbose_name='certifications')),
                ('languages', models.JSONField(default=list, verbose_name='languages')),
                ('ai_score', models.FloatField(blank=True, help_text='AI-generated profile quality score', null=True, verbose_name='AI score')),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='AI analyzed at')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cvs/', verbose_name='CV file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('file_type', models.CharField(max_length=50, verbose_name='file type')),
                ('file_size', models.IntegerField(verbose_name='file size')),
                ('extracted_text', models.TextField(blank=True, verbose_name='extracted text')),
                ('extracted_skills', models.JSONField(default=list, verbose_name='extracted skills')),
                ('ai_processed', models.BooleanField(default=False, verbose_name='AI processed')),
                ('ai_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='AI processed at')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'db_table': 'cvs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('issuer', models.CharField(max_length=255, verbose_name='issuer')),
                ('issue_date', models.DateField(verbose_name='issue date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('credential_id', models.CharField(blank=True, max_length=255, verbose_name='credential ID')),
                ('credential_url', models.URLField(blank=True, verbose_name='credential URL')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='certificate file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'db_table': 'certificates',
                'ordering': ['-issue_date'],
            },
        ),
    ]
