# Generated by Django 5.0.1 on 2025-11-26 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='job title')),
                ('description', models.TextField(verbose_name='description')),
                ('requirements', models.JSONField(default=list, help_text='List of job requirements', verbose_name='requirements')),
                ('responsibilities', models.TextField(blank=True, verbose_name='responsibilities')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('is_remote', models.BooleanField(default=False, verbose_name='remote work')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', max_length=20, verbose_name='job type')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='minimum salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum salary')),
                ('salary_currency', models.CharField(default='UZS', max_length=3, verbose_name='currency')),
                ('required_skills', models.JSONField(default=list, verbose_name='required skills')),
                ('preferred_skills', models.JSONField(default=list, verbose_name='preferred skills')),
                ('experience_years_min', models.IntegerField(default=0, verbose_name='minimum years of experience')),
                ('experience_years_max', models.IntegerField(blank=True, null=True, verbose_name='maximum years of experience')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], default='draft', max_length=20, verbose_name='status')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='application deadline')),
                ('views_count', models.IntegerField(default=0, verbose_name='views count')),
                ('applications_count', models.IntegerField(default=0, verbose_name='applications count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('employer', models.ForeignKey(limit_choices_to={'role': 'employer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='viewed at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_views', to='jobs.job')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_at'], name='jobs_status_24a2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='jobs_locatio_8650dd_idx'),
        ),
    ]
