# Generated by Django 5.0.1 on 2025-11-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('unemployment', 'Unemployment Rate'), ('job_growth', 'Job Growth'), ('skill_demand', 'Skill Demand'), ('salary_trend', 'Salary Trend')], max_length=50, verbose_name='forecast type')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='region')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='industry')),
                ('forecast_date', models.DateField(verbose_name='forecast date')),
                ('forecast_months', models.IntegerField(default=3, verbose_name='forecast months')),
                ('predicted_value', models.FloatField(verbose_name='predicted value')),
                ('confidence_score', models.FloatField(help_text='0-1 confidence score', verbose_name='confidence score')),
                ('forecast_data', models.JSONField(default=dict, help_text='Detailed forecast breakdown by month', verbose_name='forecast data')),
                ('model_version', models.CharField(max_length=50, verbose_name='model version')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='generated at')),
            ],
            options={
                'verbose_name': 'forecast data',
                'verbose_name_plural': 'forecast data',
                'db_table': 'forecast_data',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='IndustryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100, verbose_name='industry')),
                ('date', models.DateField(verbose_name='date')),
                ('total_jobs', models.IntegerField(default=0, verbose_name='total jobs')),
                ('active_jobs', models.IntegerField(default=0, verbose_name='active jobs')),
                ('avg_applications_per_job', models.FloatField(blank=True, null=True, verbose_name='avg applications per job')),
                ('total_candidates', models.IntegerField(default=0, verbose_name='total candidates')),
                ('avg_candidate_score', models.FloatField(blank=True, null=True, verbose_name='avg candidate score')),
                ('top_skills', models.JSONField(default=list, verbose_name='top skills')),
                ('avg_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='avg minimum salary')),
                ('avg_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='avg maximum salary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'industry statistics',
                'verbose_name_plural': 'industry statistics',
                'db_table': 'industry_statistics',
                'ordering': ['-date', 'industry'],
                'unique_together': {('industry', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RegionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('date', models.DateField(verbose_name='date')),
                ('total_jobs_posted', models.IntegerField(default=0, verbose_name='total jobs posted')),
                ('active_jobs', models.IntegerField(default=0, verbose_name='active jobs')),
                ('filled_positions', models.IntegerField(default=0, verbose_name='filled positions')),
                ('total_candidates', models.IntegerField(default=0, verbose_name='total candidates')),
                ('active_candidates', models.IntegerField(default=0, verbose_name='active candidates')),
                ('employed_candidates', models.IntegerField(default=0, verbose_name='employed candidates')),
                ('total_applications', models.IntegerField(default=0, verbose_name='total applications')),
                ('successful_applications', models.IntegerField(default=0, verbose_name='successful applications')),
                ('unemployment_rate', models.FloatField(blank=True, null=True, verbose_name='unemployment rate')),
                ('avg_time_to_hire_days', models.FloatField(blank=True, null=True, verbose_name='average time to hire (days)')),
                ('avg_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='average salary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'region statistics',
                'verbose_name_plural': 'region statistics',
                'db_table': 'region_statistics',
                'ordering': ['-date', 'region'],
                'unique_together': {('region', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SkillDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, verbose_name='skill name')),
                ('date', models.DateField(verbose_name='date')),
                ('jobs_requiring', models.IntegerField(default=0, verbose_name='jobs requiring')),
                ('candidates_having', models.IntegerField(default=0, verbose_name='candidates having')),
                ('supply_demand_ratio', models.FloatField(blank=True, help_text='Ratio of candidates to jobs requiring this skill', null=True, verbose_name='supply/demand ratio')),
                ('avg_salary_premium', models.DecimalField(blank=True, decimal_places=2, help_text='Average salary difference for jobs requiring this skill', max_digits=12, null=True, verbose_name='avg salary premium')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'skill demand',
                'verbose_name_plural': 'skill demands',
                'db_table': 'skill_demand',
                'ordering': ['-date', '-jobs_requiring'],
                'unique_together': {('skill_name', 'date')},
            },
        ),
    ]
