# Generated by Django 5.0.1 on 2025-11-26 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(choices=[('phone', 'Phone'), ('video', 'Video'), ('in_person', 'In Person'), ('technical', 'Technical')], default='video', max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20, verbose_name='status')),
                ('scheduled_at', models.DateTimeField(verbose_name='scheduled at')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='duration (minutes)')),
                ('location', models.CharField(blank=True, help_text='Physical location or meeting URL', max_length=255, verbose_name='location')),
                ('meeting_url', models.URLField(blank=True, verbose_name='meeting URL')),
                ('video_url', models.URLField(blank=True, help_text='URL to recorded video interview', verbose_name='video URL')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='interview_videos/', verbose_name='video file')),
                ('ai_review', models.JSONField(default=dict, help_text='AI analysis of video interview (sentiment, keywords, confidence)', verbose_name='AI review')),
                ('ai_score', models.FloatField(blank=True, null=True, verbose_name='AI score')),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='AI analyzed at')),
                ('interviewer_feedback', models.TextField(blank=True, verbose_name='interviewer feedback')),
                ('interviewer_rating', models.IntegerField(blank=True, help_text='Rating from 1-10', null=True, verbose_name='interviewer rating')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'interview',
                'verbose_name_plural': 'interviews',
                'db_table': 'interviews',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1-5', verbose_name='rating')),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_feedback', to='interviews.interview')),
            ],
            options={
                'db_table': 'interview_feedback',
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='question')),
                ('answer_text', models.TextField(blank=True, verbose_name='answer')),
                ('ai_score', models.FloatField(blank=True, null=True, verbose_name='AI score')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interview')),
            ],
            options={
                'db_table': 'interview_questions',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status', 'scheduled_at'], name='interviews_status_5a43b3_idx'),
        ),
    ]
